# -*- coding: utf-8 -*-
"""Задание по тематическим моделям. Инструмент для обучения тематических моделей.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LSjderr91gEyUBL_UU1TvKrxm7niaqu9

# Задание по тематическим моделям. Инструмент для обучения тематических моделей

---

**LSA, LDA, nmf, BERTopic|FASTopic с набором параметров, визуализация.**

1.   Подготова окружения и установка библиотек. Установка основных и доп. библиотек
"""

! pip install pandas numpy nltk spacy gensim scikit-learn pyLDAvis
! pip install tomotopy bertopic rake-nltk
! python -m nltk.downloader stopwords punkt wordnet omw-1.4
! python -m spacy download ru_core_news_sm

"""1) pandas
*   **Что делает:** Работа с таблицами и структурированными данными (DataFrame).
*   **Для чего в NLP:** Хранение, обработка и анализ данных (например, текстов с метками, результатов обработки).

2) numpy
*   **Что делает:** Высокопроизводительные числовые вычисления, работа с многомерными массивами.
*   **Для чего в NLP:** Поддержка операций с матрицами и векторами (например, мешок слов, матрицы признаков).

3) nltk (Natural Language Toolkit)
*   **Что делает:** Базовые инструменты для обработки языка: токенизация, стемминг, лемматизация, стоп-слова, корпусные данные.
*   **Для чего в NLP:** Предобработка текста, сбор лексических ресурсов, ключевые фразы (например, RAKE), POS-теги.

4) spacy
*   **Что делает:** Быстрая и качественная NLP-библиотека с поддержкой токенизации, лемматизации, POS-тегов, зависимостей.
*   **Для чего в NLP:** Глубокая предобработка текста, лемматизация, выделение сущностей, построение пайплайнов.

5) gensim
*   **Что делает:** Модели тематического моделирования (LDA, LSI), обучение векторных представлений слов (word2vec).
*   **Для чего в NLP:** Основная библиотека для тематического моделирования, обработки корпуса и работы с моделями.

6) scikit-learn
*   **Что делает:** Классические алгоритмы машинного обучения, включая векторизацию текста (CountVectorizer, TfidfVectorizer).
*   **Для чего в NLP:** Векторизация текста, кластеризация, классификация, оценка моделей.

7) pyLDAvis
*   **Что делает:** Визуализация тематических моделей (LDA).
*   **Для чего в NLP:** Интерактивный обзор тем, визуальное исследование распределения слов и документов по темам.

8) tomotopy
*   **Что делает:** Быстрая и эффективная библиотека тематического моделирования, включая LDA, HDP, Correlated Topic Models.
*   **Для чего в NLP:** Более производительные и гибкие методы тематического моделирования по сравнению с gensim.

9) bertopic
*   **Что делает:** Тематическое моделирование на основе эмбеддингов и кластеризации, часто с использованием BERT.
*   **Для чего в NLP:** Современный подход к тематическому моделированию, учитывающий контекст слов.

10) rake-nltk
*   **Что делает:** Извлечение ключевых слов и фраз из текста с помощью алгоритма RAKE.
*   **Для чего в NLP:** Быстрая и простая экстракция значимых ключевых фраз для анализа содержания текста.

11) nltk data packages (stopwords, punkt, wordnet, omw-1.4)
*   stopwords: списки часто встречающихся, но малоинформативных слов.
*   punkt: модель для разбивки текста на предложения и токены.
*   wordnet: лексическая база, используемая для синонимов и лемматизации.
*   omw-1.4: расширение WordNet для других языков.

12) ru_core_news_sm (модель spaCy)
*   **Что делает:** Модель для русского языка, включает токенизацию, лемматизацию, POS-теги, синтаксический анализ.
*   **Для чего в NLP**: Предобработка и анализ русского текста на высоком уровне.

# 2.1.  построение n-граммных моделей LDA: выделение n-грамм в корпусе, выделение ключевых выражений (RAKE), Biterm LDA 8.11. (отдельные корпусы по выбору) - я выбрала корпус "Рукопись"
"""

import os

# Путь к подпапке с .txt-файлами (уточни свой путь)
folder_path = "/content/rukopis_extracted/Rukopis"

texts = []

for root, dirs, files in os.walk(folder_path):
    for filename in files:
        if filename.endswith('.txt'):
            try:
                with open(os.path.join(root, filename), 'r', encoding='windows-1251', errors='ignore') as f:
                    texts.append(f.read())
            except Exception as e:
                print(f"Ошибка с файлом {filename}: {e}")

print(f"✅ Загружено текстов: {len(texts)}")

import nltk
import spacy
from nltk.corpus import stopwords
from gensim.utils import simple_preprocess
from gensim.models.phrases import Phrases, Phraser
from pymorphy3 import MorphAnalyzer

nltk.download('stopwords')
stop_words = set(stopwords.words("russian"))
morph = MorphAnalyzer()
nlp = spacy.load("ru_core_news_sm")

def preprocess(text):
    tokens = simple_preprocess(text, deacc=True)
    tokens = [w for w in tokens if w not in stop_words and len(w) > 2]
    lemmas = [morph.parse(token)[0].normal_form for token in tokens]
    return lemmas
#simple_preprocess(text, deacc=True) — разбивает текст на токены, приводит к нижнему регистру, удаляет пунктуацию.
#Удаляем из токенов стоп-слова и очень короткие слова (меньше 3 символов).
#Применяем морфологический разбор и лемматизацию через pymorphy3 — получаем норм форму каждого слова.
#Возвращаем список лемм (лемматизированных слов) для текстов.

processed_texts = [preprocess(text) for text in texts]

# биграммы и триграммы (фразовые выражения)
bigram = Phrases(processed_texts, min_count=5, threshold=100)
bigram_mod = Phraser(bigram)
trigram = Phrases(bigram_mod[processed_texts], threshold=100)
trigram_mod = Phraser(trigram)

#Phrases находит частые сочетания слов (например, «новый_год»), которые лучше рассматривать как единый токен.
#min_count=5 — биграмма должна встречаться минимум 5 раз, чтобы мы её признали устойчивым выражением.
#threshold=100 — порог для определения, насколько сильно слова должны быть связаны, чтобы объединиться в биграмму/триграмму.
#Phraser — оптимизированная версия для быстрого применения найденных фраз к текстам.
#Последняя строчка — применяем биграммы и триграммы к исходному корпусу, получаем тексты с фразовыми выражениями, которые будут учтены как единые токены.

texts_ngram = [trigram_mod[bigram_mod[text]] for text in processed_texts]

"""**Gensim LDA + оценка**"""

from gensim.corpora.dictionary import Dictionary
from gensim.models import LdaModel, CoherenceModel

#создание словаря (Dictionary) и корпуса (Corpus):
#filter_extremes:
#no_below=5: удаляет слова, которые встречаются в менее чем 5 документах.
#no_above=0.5: удаляет слова, которые встречаются более чем в 50% документов.
#doc2bow(text) — преобразует каждый документ в список пар (token_id, частота) → формат Bag-of-Words.

id2word = Dictionary(texts_ngram) #Dictionary слово + уникальный ID
id2word.filter_extremes(no_below=5, no_above=0.5)
corpus = [id2word.doc2bow(text) for text in texts_ngram]

#Обучение LDA-модели - вероятностная тематическая модель, которая автоматически выделяет скрытые темы в текстах.
lda_model = LdaModel(
    corpus=corpus,
    id2word=id2word,
    num_topics=10,
    random_state=100,
    passes=10, #сколько раз модель проходит по корпусу (повышает качество).
    alpha='auto' #автоматическая настройка распределения тем по документам.
)

print("🧠 Топики:")
for idx, topic in lda_model.print_topics(-1): #weight - вероятность (или вклад) слова в этой теме. Это вероятность того, что это слово будет выбрано, если случайным образом выбрать слово из темы.
    print(f"{idx}: {topic}")

coherence_model = CoherenceModel(model=lda_model, texts=texts_ngram, dictionary=id2word, coherence='c_v')
print(f"📊 Coherence Score: {coherence_model.get_coherence():.4f}")

"""**CoherenceModel** — вычисляет коэффициент согласованности (coherence), отражающий интерпретируемость тем.

**c_v** — метрика, основанная на совместной встречаемости слов в теме.

**0.2718** — это низковатое значение

**Визуализация LDA**
"""

import pyLDAvis.gensim_models
import pyLDAvis

pyLDAvis.enable_notebook()
vis = pyLDAvis.gensim_models.prepare(lda_model, corpus, id2word)
vis

"""Topic Num — номер темы (нумерация обычно начинается с 0, но тут — просто тема с индексом 4).

(..% of tokens) — означает, что примерно ..% всех слов во всём корпусе связаны с этой темой (то есть в среднем ..% слов из всего набора текстов принадлежат теме № такой-то).

**RAKE: извлечение ключевых фраз**
"""

from multi_rake import Rake

rake = Rake()
big_text = "\n".join(texts[:5])

keywords = rake.apply(big_text)

print("🔑 Ключевые фразы и их веса:")
for phrase, score in keywords:
    print(f"- {phrase} (вес: {score:.4f})")

"""**Biterm LDA** - разновидность тематического моделирования, специально разработанная для коротких текстов (таких как твиты, заголовки новостей, сообщения в мессенджерах и т.д.).

Как работает алгоритм:
- Собираются все битермы из всего корпуса.
- Модель пытается определить, какие темы объясняют со-встречаемость слов.
- Для каждой темы строится распределение слов (как в обычной LDA).
- Получается более устойчивое моделирование, особенно при малом контексте.




"""

from gensim.corpora.dictionary import Dictionary
from gensim.models import LdaModel, CoherenceModel

# Очищаем пустые документы
texts_ngram = [doc for doc in texts_ngram if len(doc) > 0]

#Создание словаря и корпуса
id2word = Dictionary(texts_ngram)
id2word.filter_extremes(no_below=2, no_above=0.7) #редкие слова (no_below=2) — встречающиеся менее чем в 2 документах, слишком частые (no_above=0.7) — встречающиеся более чем в 70% документов.
#doc2bow(text) — преобразует текст в мешок слов (bag-of-words), т.е. список (id слова, частота).
corpus = [id2word.doc2bow(text) for text in texts_ngram]

print(f"Размер словаря: {len(id2word)}")
print(f"Документов: {len(corpus)}")

lda_model = LdaModel(
    corpus=corpus,
    id2word=id2word,
    num_topics=10, #ищем 10 тем.
    random_state=100,
    passes=15, #15 проходов по корпусу для более качественного обучения.
    alpha='auto', # автоматическая настройка распределения тем по документам.
    per_word_topics=True #позволяет потом получить распределение тем по каждому слову.
)

print("🧠 Топики:")
for idx, topic in lda_model.print_topics(-1):
    print(f"{idx}: {topic}")

coherence_model = CoherenceModel(model=lda_model, texts=texts_ngram, dictionary=id2word, coherence='c_v')
#coherence='c_v' — метрика связности тем (semantic coherence). Чем выше значение (ближе к 1), тем более осмысленные и читаемые темы.
print(f"📊 Coherence Score: {coherence_model.get_coherence():.4f}")

"""CoherenceModel - Это оценка качества тем.

значения от 0.3 до 0.6 — нормальны для реальных текстов, выше — лучше.

# 2.2. добавление меток тем: labelled LDA, обучение W2V, генерация меток как предсказание модели W2V для набора слов-тематизаторов, поиск и ранжирование кандидатов в метки в Яндексе и в Википедии (ESA)) 15.11 (гиперкорпус, Пикабу)
"""

from datasets import load_dataset

dataset = load_dataset("IlyaGusev/pikabu", split="train")
for example in dataset.select(range(5)):
    print(example["text_markdown"])

"""# 2.3. Guided LDA  Hierarchical LDA 22.11 (100 великих)

**Импорт библиотек**
"""

import os
import re
import zipfile
from tqdm import tqdm
import pymorphy3
import tomotopy as tp
import pandas as pd

"""1) **import os** - Модуль для работы с операционной системой: создание и проверка папок, работа с путями к файлам, чтение списка файлов в директории и т.п.

2) **import re** - Модуль для работы с регулярными выражениями. Позволяет удобно искать, заменять и фильтровать текст (например, удалять знаки препинания, цифры и т.п.).

3) **import zipfile** - Модуль для работы с ZIP-архивами: позволяет распаковывать архивы, читать содержимое и извлекать файлы.

4) **from tqdm import tqdm** - Импорт визуального прогресс-бара для циклов. Очень удобно показывать пользователю прогресс долгих операций, например, предобработки множества текстов.

5) **import pymorphy3** - Модуль для морфологического анализа русского языка. Позволяет делать лемматизацию — приводить слова к базовой форме (например, «книги» → «книга»).

6) **import tomotopy as tp** - Томотопи — библиотека для тематического моделирования (LDA, Guided LDA, Hierarchical LDA и др.). Основной инструмент для построения тематических моделей.

7) **import pandas as pd** - Pandas — мощная библиотека для работы с табличными данными, позволяет удобно сохранять результаты, проводить анализ и экспортировать их в CSV, Excel и другие форматы.

**Загрузка текстовых данных из файлов**
"""

def load_texts_from_folder(folder_path):
    texts = []
    filenames = []
    valid_files = [f for f in os.listdir(folder_path) if f.endswith('.txt')]

    print(f"Найдено {len(valid_files)} текстовых файлов")

    for filename in tqdm(valid_files, desc="Чтение файлов"):
        file_path = os.path.join(folder_path, filename)
        try:
            # Пробуем разные кодировки
            for encoding in ['utf-8', 'cp1251', 'iso-8859-5', 'koi8-r']:
                try:
                    with open(file_path, 'r', encoding=encoding) as f:
                        text = f.read()
                        if text.strip():  # Проверяем, что файл не пустой
                            texts.append(text)
                            filenames.append(filename)
                        break
                except UnicodeDecodeError:
                    continue
        except Exception as e:
            print(f"Ошибка чтения файла {filename}: {str(e)}")

    return texts, filenames

# Указываем путь к распакованным файлам
texts_path = '/content/100great/100great_raw-20250613T191502Z-1-001/100great_raw'
texts, filenames = load_texts_from_folder(texts_path)
print(f"Успешно загружено {len(texts)} документов")

"""**Предобработка текста**"""

morph = pymorphy3.MorphAnalyzer()

# Расширенный список стоп-слов для русского языка
russian_stopwords = {
    'и', 'в', 'во', 'не', 'что', 'он', 'на', 'я', 'с', 'со', 'как', 'а', 'то', 'все', 'она', 'так', 'его',
    'но', 'да', 'ты', 'к', 'у', 'же', 'вы', 'за', 'бы', 'по', 'только', 'ее', 'мне', 'было', 'вот', 'от',
    'меня', 'еще', 'нет', 'о', 'из', 'ему', 'теперь', 'когда', 'даже', 'ну', 'вдруг', 'ли', 'если', 'уже',
    'или', 'ни', 'быть', 'был', 'него', 'до', 'вас', 'нибудь', 'опять', 'уж', 'вам', 'ведь', 'там', 'потом',
    'себя', 'ничего', 'ей', 'может', 'они', 'тут', 'где', 'есть', 'надо', 'ней', 'для', 'мы', 'тебя', 'их',
    'чем', 'была', 'сам', 'чтоб', 'без', 'будто', 'чего', 'раз', 'тоже', 'себе', 'под', 'будет', 'ж', 'тогда',
    'кто', 'это', 'того', 'потому', 'этого', 'какой', 'совсем', 'ним', 'здесь', 'этом', 'один', 'почти', 'мой',
    'тем', 'чтобы', 'нее', 'сейчас', 'были', 'куда', 'зачем', 'всех', 'никогда', 'можно', 'при', 'наконец',
    'два', 'об', 'другой', 'хоть', 'после', 'над', 'больше', 'тот', 'через', 'эти', 'нас', 'про', 'всего', 'них',
    'какая', 'много', 'разве', 'три', 'эту', 'моя', 'впрочем', 'хорошо', 'свою', 'этой', 'перед', 'иногда',
    'лучше', 'чуть', 'том', 'нельзя', 'такой', 'им', 'более', 'всегда', 'конечно', 'всю', 'между'
}

def preprocess_ru(text):
    # Удаляем специальные символы и цифры
    text = re.sub(r'[^а-яА-ЯёЁ\s]', '', text.lower())
    text = re.sub(r'\d+', '', text)

    # Токенизация по пробелам
    tokens = text.split()

    # Лемматизация и фильтрация
    lemmas = []
    for token in tokens:
        if len(token) > 2 and token not in russian_stopwords:
            try:
                parsed = morph.parse(token)[0]
                lemma = parsed.normal_form
                lemmas.append(lemma)
            except Exception:
                # В случае ошибки просто пропускаем слово
                continue
    return lemmas

print("Начата предобработка текстов...")
processed_texts = [preprocess_ru(text) for text in tqdm(texts, desc="Предобработка")]
print("Предобработка завершена!")

"""Создаем морфологический анализатор (pymorphy3.MorphAnalyzer()), чтобы потом приводить слова к их нормальной форме — лемматизировать.

Определяем список стоп-слов — частых служебных слов русского языка, которые обычно не несут смысловой нагрузки для анализа.

**В функции preprocess_ru для каждого текста:**
*   Приводим весь текст к нижнему регистру и очищаешь от всех символов, кроме русских букв и пробелов.
*   Убираем цифры.
*   Делим текст на слова (токены).

**Для каждого слова:**
*   Пропускаем слишком короткие и стоп-слова.
*   Лемматизируем слово — приводим к нормальной словарной форме.
*   Сохраняем леммы в итоговый список.
*   Применяем эту функцию ко всем текстам, получая список уже очищенных и лемматизированных текстов — готовых к тематическому моделированию или другому анализу.

**Этап обучения тематической модели LDA с использованием семенных слов (seed words), имитируя подход Guided LDA.**
"""

seed_map = {
    0: {'писатель', 'поэт', 'роман', 'стих', 'литература', 'творчество'},
    1: {'ученый', 'открытие', 'наука', 'физика', 'изобретение', 'исследование'},
    2: {'полководец', 'война', 'сражение', 'армия', 'победа', 'стратегия'}
}

print("Обучаем обычную LDA (имитация Guided LDA)...")
lda = tp.LDAModel(k=10, min_cf=5)

for doc in processed_texts:
    lda.add_doc(doc)

lda.train(1000)

# Анализируем темы и ищем пересечения с seed-словами
print("\nСопоставление seed-тем с выявленными темами:")
for k in range(lda.k):
    topic_words = set(word for word, _ in lda.get_topic_words(k, top_n=15))
    matched_seeds = [tid for tid, seeds in seed_map.items() if len(topic_words.intersection(seeds)) > 0]
    print(f"Тема {k}: топ-слова: {[w for w, _ in lda.get_topic_words(k, top_n=10)]}")
    if matched_seeds:
        print(f"  Пересекается с seed-темами: {matched_seeds}")
    else:
        print("  Не пересекается с seed-темами")

"""Определение **seed_map** — словаря с ключами-темами и множествами ключевых слов (seed-слов), которые отражают заранее известные темы, которые мы хотим найти в данных, например:
*   **Тема 0** — литература и творчество (писатель, поэт, роман и т.д.)
*   **Тема 1** — наука и открытия (ученый, физика и др.)
*   **Тема 2** — война и стратегия (полководец, армия и др.)


Создание модели LDA с 10 темами (k=10), параметром min_cf=5 (минимальное количество документов, в которых должно встречаться слово, чтобы участвовать в модели).

Добавление документов в модель — сюда поступают уже обработанные (лемматизированные) тексты.

Обучение модели LDA — методом итераций (1000 итераций).
**Итерация** - это один проход или шаг в процессе обучения модели.

Анализ результатов:

Для каждой темы из модели берутся топ-15 слов.

Сравниваются эти слова с seed-словами из seed_map.

Если пересечения есть — значит тема частично совпадает с заранее определённой тематикой.

Выводятся топовые слова каждой темы и информация о пересечении с seed-темами.


---

Темы 4, 6 и 8 частично совпадают с seed-темами:

Тема 4 совпадает с темой науки (seed_map ключ 1: «учёный», «исследование», «наука» и т.п.)

Темы 6 и 8 совпадают с темой войны и армии (seed_map ключ 2: «армия», «война», «военный» и др.)

**Анализ и визуализация результатов обучения Hierarchical LDA, или интерпретация иерархических тем.**
"""

print("\nИерархия тем (Hierarchical LDA):")

# Собираем все пути по дереву тем из документов
paths = [doc.path for doc in hlda.docs]

# Подсчет тем иерархии
from collections import defaultdict, Counter

topic_paths = defaultdict(list)
for path in paths:
    for depth, topic_id in enumerate(path):
        topic_paths[depth].append(topic_id)

# Для каждой темы на каждом уровне выводим топ-слова
for depth in sorted(topic_paths.keys()):
    counter = Counter(topic_paths[depth])
    print(f"\n=== Уровень {depth} ===")
    for topic_id, count in counter.most_common():
        top_words = [w for w, _ in hlda.get_topic_words(topic_id, top_n=10)]
        print(f"Тема {topic_id} (встречается в {count} документах): {', '.join(top_words)}")

"""**Получение путей тем для документов:**

Каждый документ в hlda.docs имеет атрибут .path — это список с ID тем, по которым документ «проходит» от корня до листа в иерархии тем.

Например, путь [0, 3, 7] — документ относится к теме 0 на уровне 0, теме 3 на уровне 1 и теме 7 на уровне 2.

**Группировка тем по уровням и подсчёт встречаемости:**
Для каждого уровня (глубины) собираются все ID тем из путей документов, считается, сколько документов относится к каждой теме на этом уровне.

**Вывод тем по уровням:**
Для каждого уровня и каждой темы выводятся:
*   ID темы
*   Количество документов, которые принадлежат этой теме на данном уровне
*   Топ-10 слов темы — ключевые слова, описывающие тему.

---

**Уровень 0 (корень)**: всего одна тема — очень общая, с топ-словами типа «который», «свой», «время», «один», «человек». Эти слова — часто служебные и универсальные, что говорит о недостаточной фильтрации стоп-слов или о том, что на этом уровне модель выделила очень широкую, обобщающую тему.

---



**Уровень 1 — крупные тематические кластеры**
Здесь появляется много разных тем, каждая с разной частотой (1 или 2 документа). Они уже тематически более конкретны, например:

**Тема 8** — «картина», «художник», «полотно», «жизнь» — тема искусства, живописи.

**Тема 15** — «бог», «миф», «богиня», «древний» — мифология, религия.

**Тема 24, 25, 9** — темы, связанные с годами, историей, архитектурой, наукой, техникой (ракеты, самолёты).

**Тема 31, 26, 27, 28, 29** — военная тематика: армия, война, сражения, заговоры, корабли.

**Тема 14** — «учёный», «физика», «наука» — научная тематика.

**Тема 30, 41, 10, 49** — театр, кино, актёрство, художественные искусства.

Каждая из этих тем более предметна, хотя часто встречаются служебные слова («который», «год», «свой»), которые можно было бы дополнительно фильтровать.

---



**Уровень 2 — более узкие подкатегории**
На этом уровне темы ещё более детализированы и специфичны. Примеры:

**Тема 16** — живопись, портрет, композиция — подкатегория живописи (от темы 8).

**Тема 33** — техника: «машина», «двигатель», «ток» — узкая тема техники/механики.

**Тема 23** — философия, наука, мысль — интеллектуальные и философские идеи.

**Тема 32, 48, 17** — археология, архитектура, строительство.

**Тема 19, 22, 35, 36** — военная тематика, награды, исторические личности, заговоры.

**Тема 38, 18, 21, 49** — искусство, театр, музыка, роли.

**Тема 20** — природа, море, растения, птицы.

**Тема 39, 37** — военно-морская тематика: флот, корабли, бои.

# 2.4.Dynamic LDA  29.11 (Исторические корпусы + Рукопись...)
"""

import os

corpus_1_path = '/content/corpus_1/Rushist_raw'
corpus_2_path = '/content/corpus_2/Rukopis'

print("Содержимое corpus_1_path:", os.listdir(corpus_1_path))
print("Содержимое corpus_2_path:", os.listdir(corpus_2_path))

# --- Считаем количество документов в историческом корпусе ---
files_corpus_1 = [f for f in os.listdir(corpus_1_path) if os.path.isfile(os.path.join(corpus_1_path, f))]
print(f"Файлы в историческом корпусе ({corpus_1_path}): {files_corpus_1}")
time_slices_corpus_1 = [len(files_corpus_1)]

# --- Считаем количество документов по неделям в рукописи ---
weeks = [d for d in os.listdir(corpus_2_path) if d.startswith('week')]
weeks = sorted(weeks, key=lambda x: int(x[4:]))
print(f"Недели в рукописи: {weeks}")

time_slices_corpus_2 = []
for week in weeks:
    week_path = os.path.join(corpus_2_path, week)
    files = [f for f in os.listdir(week_path) if os.path.isfile(os.path.join(week_path, f))]
    print(f"Файлы в {week}: {files}")
    time_slices_corpus_2.append(len(files))

# --- Объединяем ---
time_slices = time_slices_corpus_1 + time_slices_corpus_2

print(f"Исторический корпус (1 срез): {time_slices_corpus_1}")
print(f"Рукопись (по неделям): {time_slices_corpus_2}")
print(f"Объединённый time_slices: {time_slices}")

import re
from razdel import tokenize
from nltk.corpus import stopwords
import nltk

nltk.download('stopwords')
stop_words = set(stopwords.words('russian'))

def preprocess(text):
    text = text.lower()
    text = re.sub(r'\W', ' ', text)  # только буквы и цифры
    tokens = [token.text for token in tokenize(text)]
    tokens = [t for t in tokens if t not in stop_words and len(t) > 2]
    return tokens

all_tokens = [preprocess(doc) for doc in all_texts]
print(f'Обработано документов: {len(all_tokens)}')
print(f'Пример токенов из первого документа:\n{all_tokens[0]}')

from gensim import corpora

dictionary = corpora.Dictionary(all_tokens)
dictionary.filter_extremes(no_below=5, no_above=0.5)
corpus = [dictionary.doc2bow(text) for text in all_tokens]

from gensim.corpora.dictionary import Dictionary
from gensim.models.ldamulticore import LdaMulticore

num_topics = 10  # можно менять
passes = 10      # количество проходов по корпусу
workers = 2      # количество потоков

start_idx = 0
lda_models = []
dictionaries = []
corpora = []

for slice_len in time_slices:
    docs_slice = all_tokens[start_idx:start_idx + slice_len]
    start_idx += slice_len

    # Создаём словарь и корпус
    dictionary = Dictionary(docs_slice)
    corpus = [dictionary.doc2bow(doc) for doc in docs_slice]

    # Обучаем LDA
    lda = LdaMulticore(corpus, id2word=dictionary, num_topics=num_topics, passes=passes, workers=workers)

    lda_models.append(lda)
    dictionaries.append(dictionary)
    corpora.append(corpus)

    print(f"Обучена LDA на срезе с {slice_len} документов")

for i, lda in enumerate(lda_models):
    print(f"\nТемы для временного среза {i+1} ({time_slices[i]} документов):")
    for topic_id, topic in lda.show_topics(num_topics=num_topics, num_words=7, formatted=False):
        topic_words = ", ".join([word for word, _ in topic])
        print(f"Тема {topic_id}: {topic_words}")

"""# 2.5. Author-Topic Model 6.12 (корпус СМИ + Дом, в котором)"""

import pandas as pd

csv_path = "/content/content_csv/content.csv"
df_news = pd.read_csv(csv_path, header=0)

print("Столбцы:", df_news.columns.tolist())
df_news.head(1)

df_news = pd.read_csv(csv_path, header=None)
df_news.columns = ['url', 'text', 'keywords']
print(df_news.columns)
df_news.head(1)

dom_text = "/content/corpus_dom/116583595.txt"

with open(dom_text, 'r', encoding='cp1251') as f:
    dom_text = f.read()

print(f"📖 Фрагмент 'Дом, в котором':\n{dom_text[:500]}...")

documents = []

# Добавим статьи из новостей
for text in df_news['text']:
    documents.append({'author': 'news_author', 'text': text})

# Добавим "Дом, в котором"
documents.append({'author': 'dom_author', 'text': dom_text})

!pip install gensim==4.3.2 nltk==3.8.1 pymorphy3==1.2.0

import re
import nltk
import pandas as pd
import numpy as np
from nltk.corpus import stopwords
from gensim.corpora import Dictionary
from gensim.models import AuthorTopicModel
import pymorphy3  # Используем pymorphy3

# Убедимся, что стоп-слова загружены
nltk.download('stopwords', quiet
import re
import nltk
import pandas as pd
from nltk.corpus import stopwords
from nltk.stem import SnowballStemmer
from gensim.corpora import Dictionary
from gensim.models import AuthorTopicModel

# Загрузка стоп-слов
nltk.download('stopwords')
russian_stopwords = stopwords.words('russian')
stemmer = SnowballStemmer('russian')

# Функция предобработки текста
def preprocess_text(text):
    # Приведение к нижнему регистру и удаление небуквенных символов
    text = re.sub(r'[^а-яё\s]', '', text.lower())
    tokens = text.split()

    # Фильтрация и стемминг
    processed_tokens = [
        stemmer.stem(token)
        for token in tokens
        if token not in russian_stopwords and len(token) > 3
    ]
    return processed_tokens

# Разбиение большого текста на фрагменты
def split_text(text, chunk_size=10000):
    return [text[i:i+chunk_size] for i in range(0, len(text), chunk_size)]