# -*- coding: utf-8 -*-
"""Инструмент для оценки сложности текстов.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16lsTCx-N50OEY7DjglMP4aKUdYld1Xvc

# **Инструмент для оценки сложности текстов**
"""

!pip install textstat #Предназначена для оценки читаемости и сложности текста.
#Считает классические метрики читаемости: Flesch Reading Ease, Flesch-Kincaid Grade, Gunning Fog, SMOG
!pip install ruts #Библиотека для оценки сложности русского текста, разработанная специально для русского языка.

import os
from ruts.readability_stats import ReadabilityStats #для расчёта метрик сложности текста из библиотеки ruts
import pandas as pd
import textstat #для расчёта других метрик сложности текста

folder_path = '/content/10 статей для оценки сложности текстов/10 статей для генерации аннотаций'

results = []

for filename in sorted(os.listdir(folder_path)):
    if filename.endswith('.txt'):
        filepath = os.path.join(folder_path, filename)
        print(f"Обрабатываю файл: {filepath}")
        with open(filepath, 'r', encoding='utf-8') as f:
            text = f.read()

        # Ruts
        stats = ReadabilityStats(text)
        data = stats.get_stats() #Метод get_stats() возвращает словарь с разными метриками сложности, рассчитанными ruts

        # Textstat
        data_textstat = {
            'textstat_gunning_fog': textstat.gunning_fog(text),
            'textstat_dale_chall': textstat.dale_chall_readability_score(text),
            'textstat_automated_readability_index': textstat.automated_readability_index(text),
            'textstat_flesch_reading_ease': textstat.flesch_reading_ease(text),
            'textstat_smog_index': textstat.smog_index(text),
            'textstat_coleman_liau_index': textstat.coleman_liau_index(text),
        }

        # Объединяем данные
        data.update(data_textstat)
        data['filename'] = filename

        results.append(data)

df = pd.DataFrame(results)

print(df.head())

df.to_csv('readability_comparison.csv', index=False)

# Вывод таблицы
df = pd.DataFrame(results)
pd.set_option('display.max_columns', None)
df.head(10)

# @title flesch_reading_easy

from matplotlib import pyplot as plt
df['flesch_reading_easy'].plot(kind='hist', bins=20, title='flesch_reading_easy')
plt.gca().spines[['top', 'right',]].set_visible(False)

# @title flesch_kincaid_grade

from matplotlib import pyplot as plt
df['flesch_kincaid_grade'].plot(kind='line', figsize=(8, 4), title='flesch_kincaid_grade')
plt.gca().spines[['top', 'right']].set_visible(False)

import pandas as pd

# Данные по метрикам
data = [
    ["flesch_kincaid_grade", "ruts", "Уровень читаемости в 'классах школы'", "~1–18+", "✅ Да", "Подходит, если используется через `ruts` — адаптирован"],
    ["flesch_reading_easy", "ruts", "Уровень читаемости: чем выше — тем проще", "0–100+", "✅ Да", "Значения 60–70 — норма; >80 — легко; <30 — трудно"],
    ["coleman_liau_index", "ruts", "Уровень сложности по длине слов и предложений", "~1–18+", "✅ Да", "Нормально интерпретируется для русского"],
    ["smog_index", "ruts", "Фокус на полисиллабах (длинных словах)", "~3–30", "✅ Да", "Надёжный индикатор сложности"],
    ["automated_readability_index", "ruts", "Уровень класса читаемости, похож на FK и CLI", "~1–20", "✅ Да", "Даёт высокие значения на научных текстах"],
    ["lix", "ruts", "Индекс сложности: длина предложений + доля длинных слов", ">60 — сложно", "✅ Да", "Хорошо подходит для русского"],
    ["gunning_fog", "textstat", "Доля сложных слов и длина предложений", "~4–20+", "⚠️ Нет", "Разработан для английского, но иногда используется и в русском"],
    ["dale_chall_readability_score", "textstat", "Основан на списке 'простых слов' (английский)", "0–10", "❌ Нет", "**Неприменим для русского**, даёт бессмысленные значения (20+)"],
    ["automated_readability_index", "textstat", "То же, что и в `ruts`, но считает по-английски", "1–20", "⚠️ Нет", "Переоценивает сложность русских текстов"],
    ["flesch_reading_ease", "textstat", "Версия индекса Флеша для английского", "0–100+", "❌ Нет", "Даёт **слишком высокие** или бессмысленные значения"],
    ["smog_index", "textstat", "Требует ≥3 предложений, считает по-английским правилам", "~4–20", "⚠️ Нет", "Для коротких русских текстов не работает стабильно"],
    ["coleman_liau_index", "textstat", "Считает на основе букв и предложений", "~1–18", "⚠️ Нет", "Значения завышены, но тренд может быть полезен"],
]

# Создание DataFrame
columns = ["Метрика", "Библиотека", "Что измеряет", "Диапазон значений", "Для русского?", "Комментарий"]
df_metrics = pd.DataFrame(data, columns=columns)

# Вывод таблицы
df_metrics.style.set_properties(**{
    'text-align': 'left',
    'white-space': 'pre-wrap'
}).set_table_styles([{
    'selector': 'th',
    'props': [('text-align', 'left')]
}])

import pandas as pd

# Загрузим уже сохраненный файл (если нужно)
df = pd.read_csv('readability_comparison.csv')

# Покажем первые строки
print(df.head())

# Посчитаем средние значения по метрикам (без filename)
print("\nСредние значения метрик по всем текстам:")
print(df.drop(columns=['filename']).mean())

# Отсортируем по одной из метрик, например по textstat_gunning_fog
print("\nТоп 5 самых сложных текстов по Gunning Fog:")
print(df.sort_values(by='textstat_gunning_fog', ascending=False).head())

# Сохраняем в CSV (если еще не сохранили)
df.to_csv('readability_comparison.csv', index=False)
print("Результаты сохранены в readability_comparison.csv")