# -*- coding: utf-8 -*-
"""Инструмент для автоматического разрешения неоднозначности.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kk0WMD4td-QvhZUGBpI3mVo-9QxaXSF6

# **Инструмент для автоматического разрешения неоднозначности**
"""

!pip install numpy scikit-learn compress-fasttext xmltodict matplotlib
# numpy - для работы с числовыми массивами и матрицами
#scikit-learn - библиотека машинного обучения (здесь нужна для KDTree) - структура данных для эффективного поиска ближайших соседей в многомерном пространстве.
#compress-fasttext - сжатые версии FastText моделей - библиотека для эффективного обучения векторным представлениям слов (word embeddings) и классификации текста.
#xmltodict - для работы с XML-данными (используется внутри RuWordNet)
#matplotlib - для визуализации

from ruwordnet import RuWordNet
wn = RuWordNet() # Загружаем RuWordNet (русская семантическая сеть)
# Синсеты (группы синонимичных понятий)
# Связи между понятиями (гиперонимы, гипонимы и др.)
# Лексические единицы (слова и их значения)

len(wn.synsets), len(wn.senses) # Возвращает кортеж вида: (количество_синсетов, количество_смыслов)

#Синсет (synset) - это группа слов, выражающих одно понятие.

"""# Использование RuWordNet как семантического тезауруса для исследования различных типов отношений между словами и их значениями"""

for sense in wn.get_senses('ключ'):
    print(sense.synset)

#выводятся все значения слова 'ключ'

wn.get_senses('ключ')[0].synset.hypernyms

# Берём первый смысл слова ключ (wn.get_senses('ключ')[0]) и смотрим его гиперонимы — более общие понятия,
# к которым относится этот смысл 'ключа'

wn.get_senses('манго')[0].synset.hypernyms

# также смотрим гиперонимы для первого смысла слова 'манго'

wn.get_senses('ананас')

#Получаем все возможные значения (сенсы) для слова 'ананас'

fruit = wn.get_senses('манго')[0].synset.hypernyms[0]
fruit

# Сохраняем первый гипероним для первого смысла слова 'манго' в переменную fruit
# Теперь fruit — это более общее понятие, к которому относится 'манго'

fruit.hyponyms

# Получаем все гипонимы (подчинённые, более частные понятия) для этого гиперонима 'fruit'
# Это позволит увидеть все слова, которые относятся к той же категории, что и 'манго'

senses = wn.get_senses('ананас')  # Получаем список сенсов (значений)

for sense in senses:
    synset = sense.synset  # Получаем synset для этого сенса
    print(f"Sense id: {sense.id}, Name: {sense.name}")
    print(f"Synset id: {synset.id}, Title: {synset.title}")
    print('---')

"""# Анализ семантических связей

Домен – Атрибут (domains / domain_items)
"""

import random
# автомобиль — домены (темы)
print(wn['автомобиль'][0].synset.domains)
# Выводит тематику для слова "автомобиль"

#Случайные слова из домена "автомобиль"
domains = wn['автомобиль'][0].synset.domains
if domains:
    domain = domains[0]
    print(random.sample(domain.domain_items, min(len(domain.domain_items), 10)))

"""Часть - целое"""

# Части автомобиля — меронимы
print(wn['автомобиль'][0].synset.meronyms)

# Автомобиль как часть чего-то — холонимы
print(wn['бампер'][0].synset.holonyms)

"""Класс - экземпляр"""

# Слово: волга — классы (реки России)
print(wn['волга'][0].synset.classes)

# Слово: город — экземпляры
print(random.sample(wn['город'][0].synset.instances, 10))

"""Причина - следствие"""

# причины и следствия для глаголов устать и выключить
print(wn['устать'][0].synset.causes)
print(wn['выключить'][0].synset.effects)

"""Синонимы"""

[s for ss in wn['построить'][0].synset.pos_synonyms for s in ss.senses]

"""Антонимы"""

wn['глупый'][0].synset.antonyms

"""Фразы и их составляющие"""

wn['глупый'][0].phrases

wn['глупый человек'][0].words

"""Однокоренные слова"""

# Однокоренные слова для "красный"
print(wn['красный'][0].derivations)

"""# Предсказание гиперонимов для слов с помощью FastText и RuWordNet"""

# Commented out IPython magic to ensure Python compatibility.
!pip uninstall -y numpy
!pip install numpy==1.24.4
!pip install compress-fasttext
import numpy as np #библиотека для работы с массивами, матрицами и числовыми операциями.
import compress_fasttext #библиотека для загрузки и использования сжатых векторных моделей FastText

from collections import Counter #класс для быстрого подсчёта частот элементов (например, слов в тексте)
from sklearn.neighbors import KDTree #структура данных для поиска ближайших векторов в многомерном пространстве.

import matplotlib.pyplot as plt #модуль для визуализации данных (точек, графов, кластеров)
# %matplotlib inline

# Загружаем сжатую модель FastText (векторное представление слов)
ft = compress_fasttext.models.CompressedFastTextKeyedVectors.load(
    'https://github.com/avidale/compress-fasttext/releases/download/gensim-4-draft/geowac_tokens_sg_300_5_2020-100K-20K-100.bin'
)

def vectorize(text):
    vec = np.mean([ft[word] for word in text.lower().split() if len(word) >= 3], axis=0)
    vec /= sum(vec**2) ** 0.5
    return vec

def distance2vote(d, a=3, b=5):
    sim = np.maximum(0, 1 - d**2/2)
    return np.exp(-d**a) * sim **b

x = np.linspace(0, 1)
plt.plot(x, distance2vote(x))
plt.xlabel('Расстояние до соседа')
plt.ylabel('Вес голоса соседа')
plt.title('Функция взвешивания соседей');

!pip install ruwordnet
!ruwordnet download
from ruwordnet import RuWordNet
wn = RuWordNet()
from tqdm.auto import tqdm, trange
words, vectors, synset_ids = [], [], []
for synset in tqdm(wn.synsets):
    if synset.part_of_speech != 'V':
        continue
    for sense in synset.senses:
        words.append(sense.name)
        vectors.append(vectorize(sense.name))
        synset_ids.append(synset.id)
vectors = np.stack(vectors)
tree = KDTree(vectors)

votes = Counter()
dists, ids = tree.query(vectorize('кашлять').reshape(1, -1), k=100)
for idx, distance in zip(ids[0], dists[0]):
    for hyper in wn[synset_ids[idx]].hypernyms:
        votes[hyper.id] += distance2vote(distance)
    print(words[idx], [t.title for t in wn[synset_ids[idx]].hypernyms])

for sid, score in votes.most_common(10):
    print(score,  wn[sid].title)

"""**RuWordNet** — это "словарь смыслов" для русского языка.

Мы используем **FastText**, чтобы представить каждое слово как вектор (набор чисел).

С помощью **KDTree** мы ищем похожие слова.

Затем мы предсказываем гиперонимы — более общие категории для данного слова.

# Лишние слова
"""

import math
from ruwordnet import RuWordNet
wn = RuWordNet()

words = ['аккумулятор', 'двигатель', 'колесо', 'сметана']

def get_all_hypernyms(wn, word, max_level=100):
    """Получить все гиперонимы слова с уровнями (расстояниями)"""
    senses = wn.get_senses(word.lower())
    front = [s.synset for s in senses]
    levels = {}
    for level in range(max_level):
        if not front:
            break
        new_front = []
        for synset in front:
            if synset.id not in levels:
                levels[synset.id] = level
                new_front.extend(synset.hypernyms)
        front = new_front
    return levels

def get_closest_common(levels1, levels2):
    """Ближайший общий гипероним и суммарное расстояние"""
    best_id, best_dist = None, math.inf
    for id1, dist1 in levels1.items():
        if id1 in levels2:
            total = dist1 + levels2[id1]
            if total < best_dist:
                best_id, best_dist = id1, total
    return best_id, best_dist

# Матрица расстояний
print('\t\t' + '\t'.join([w.upper() for w in words]))
for w1 in words:
    print(w1.upper(), end='\t')
    for w2 in words:
        d = get_closest_common(
            get_all_hypernyms(wn, w1),
            get_all_hypernyms(wn, w2)
        )[1]
        print(d if d is not None else '-', end='\t\t')
    print()

# Поиск "лишнего" слова
distances = {}
for w1 in words:
    total = 0
    for w2 in words:
        if w1 == w2:
            continue
        _, d = get_closest_common(
            get_all_hypernyms(wn, w1),
            get_all_hypernyms(wn, w2)
        )
        total += d if d is not None else 100
    distances[w1] = total / (len(words) - 1)

odd_one = max(distances.items(), key=lambda x: x[1])
print(f'Лишнее слово: {odd_one[0].upper()} (ср. расстояние: {odd_one[1]:.2f})')

"""# Определение значения слова в контексте (WSD — Word Sense Disambiguation)"""

!pip install razdel

import numpy as np
import razdel  # для токенизации текста
from ruwordnet import RuWordNet

# Загружаем RuWordNet
wn = RuWordNet()

# Функция для векторизации текста (среднее по словам, исключая короткие)
def vectorize(text, ft):
    vecs = [ft[word] for word in text.lower().split() if len(word) >= 3 and word in ft]
    if not vecs:
        return np.zeros(ft.vector_size)
    vec = np.mean(vecs, axis=0)
    return vec / np.linalg.norm(vec)

# Функция для определения правильного смысла слова в контексте
def disambiguate(word, context, wn, ft):
    candidates = [sense.synset for sense in wn[word]]
    # Векторизуем контекст (без самой слова)
    context_tokens = [t.text for t in razdel.tokenize(context) if t.text.lower() != word.lower()]
    context_vector = vectorize(' '.join(context_tokens), ft)

    scores = {}
    for synset in candidates:
        # Векторизуем все синонимы синонима
        synonyms = ' '.join(sense.name for sense in synset.senses)
        synset_vector = vectorize(synonyms, ft)
        # Косинусное сходство между контекстом и синонимами
        score = np.dot(context_vector, synset_vector)
        scores[synset] = score

    # Выбираем смысл с максимальным баллом
    best_sense = max(scores, key=scores.get)
    return best_sense, scores[best_sense]

# Пример использования
context = "Мозг является ключом ко всем вопросам"
word = "ключ"

best_sense, score = disambiguate(word, context, wn, ft)
print(f"Лучший смысл: {best_sense.title}, оценка: {score}")

"""Здесь мы определяем правильное значение слова в предложении. Используем RuWordNet для вариантов значений и fastText для сравнения смысла слов через векторы. Программа выбирает значение, которое лучше всего подходит к контексту. - НЕВЕРНОЕ ОПРЕДЕЛЕНИЕ

# Разрешение лексической многозначности
"""

!pip install fasttext
!wget -O ft_model.bin https://github.com/avidale/compress-fasttext/releases/download/gensim-4-draft/geowac_tokens_sg_300_5_2020-100K-20K-100.bin

from ruwordnet import RuWordNet
wn = RuWordNet('ruwordnet.db')

import compress_fasttext
ft = compress_fasttext.models.CompressedFastTextKeyedVectors.load('ft_model.bin')

import numpy as np
import razdel
from ruwordnet import RuWordNet

wn = RuWordNet()

"""**Функция векторизации текста**"""

def vectorize(text, ft):
    words = [w for w in text.lower().split() if len(w) >= 3 and w in ft]
    if not words:
        return np.zeros(ft.vector_size)
    vec = np.mean([ft[w] for w in words], axis=0)
    return vec / np.linalg.norm(vec)

"""**Функция дизамбигуации значений**"""

def disambiguate(word, context, ft):
    candidates = [s.synset for s in wn[word]]
    context_words = [t.text for t in razdel.tokenize(context) if t.text.lower() != word.lower()]
    text_vector = vectorize(' '.join(context_words), ft)

    candidate_vectors = []
    for c in candidates:
        syn_words = []
        for s in c.senses:
            for w in s.name.lower().split():
                if w != word.lower():
                    syn_words.append(w)
        candidate_vectors.append(vectorize(' '.join(syn_words), ft))

    scores = [np.dot(text_vector, v) for v in candidate_vectors]
    return sorted(zip(scores, candidates), reverse=True)

context = '''Рыбак поймал сетью рыбу'''
word = 'сеть'

result = disambiguate(word, context, ft)

for score, synset in result:
    print(f'{score:.3f} — {synset.id} — {synset.title}')

context = '''По сети он отправил мне данные и файлы'''
word = 'сеть'

result = disambiguate(word, context, ft)

for score, synset in result:
    print(f'{score:.3f} — {synset.id} — {synset.title}')