# -*- coding: utf-8 -*-
"""Notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VRuzk6oyGwSU4eka_I0l-U8ECi-t04b5

## **Language Identification**
"""

!pip install langid

import langid

with open('Monkeys.txt', 'r', encoding='utf-8') as f:
  my_file = f.read()

for i in my_file:
    print(langid.classify(i))

with open('Der perfekte Dominoeffekt.txt', 'r', encoding='utf-8') as f:
  my_file1 = f.read()

for i in my_file1:
    print(langid.classify(i))

! pip install langdetect

from langdetect import detect_langs
detect_langs(my_file)

from langdetect import detect_langs
detect_langs(my_file1)

