# -*- coding: utf-8 -*-
"""Hierarchical TM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l2CSxABTr1Sk153KZldK3SgVZ-C3Gz7X
"""

!pip install bertopic

from bertopic import BERTopic
from sklearn.datasets import fetch_20newsgroups

docs = fetch_20newsgroups(subset='all',  remove=('headers', 'footers', 'quotes'))["data"]
topic_model = BERTopic(verbose=True)
topics, probs = topic_model.fit_transform(docs)

hierarchical_topics = topic_model.hierarchical_topics(docs)

topic_model.visualize_hierarchy(hierarchical_topics=hierarchical_topics)