# -*- coding: utf-8 -*-
"""Инструмент для поиска контекстов целевого слова с обработкой лексических, семантических и морфологических маркеров.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EIgRTW8LLjKWilkWHQ8t70nS_3f81vWa

# Инструмент для поиска контекстов целевого слова с обработкой лексических, семантических и морфологических маркеров
"""

with open('/content/Контексты 2.txt', encoding='utf-8') as f:
    raw_text = f.read()

# Разбить по двойным переносам строк (пустая строка между абзацами)
context = [p.strip() for p in raw_text.split('\n\n') if p.strip() != '']

print(f'Количество контекстов: {len(context)}')

print(len(context))
print(context[:500])  # первые 500 символов

"""Каждый из контекстов состоит из слов, которые заключены в теги <w></w>, а вся информация (лемма, грамматика и семантика) заключена в теге <ana> (атрибуты lex, gr, sem соответственно)."""

contextt_str = ''.join(context)
pattern = r'<w>.+?</w>' #Регулярное выражение с «ленивым» (нежадным) квантификатором '?'.
#Получаем список всех отдельных слов, оформленных в теги
words = re.findall(pattern, context_str)
for word in words:
    print(word)

tokens = []
for word in words:

    # Ищем лексему
    lex_pattern = r"lex='.+?'"
    lex_match = re.search(lex_pattern, word)
    if lex_match:
        lex_raw = lex_match.group()
        lex = lex_raw.split('=')[1].strip("'")
        print('Лексема: ' + lex)
    else:
        print('Лексема не найдена в:', word)

    # Ищем словоформу
    form_pattern = r'>([А-Яа-яёЁ]+)<'
    form_match = re.search(form_pattern, word)
    if form_match:
        form = form_match.group(1)
        tokens.append(form)
        print('Словоформа: ' + form)
    else:
        print('Словоформа не найдена в:', word)

    # Ищем семантику
    sem_pattern = r"sem='.+?'"
    sem_match = re.search(sem_pattern, word)
    if sem_match:
        sem = sem_match.group().split('=')[1].strip("'")
        print('Семантика: ' + sem)
    else:
        print('Семантика не найдена в:', word)

    print('_____________________')

sentence = ' '.join(tokens)
print(sentence)

"""**Функция предобработки preprocess** - на вход получает контекст в сыром виде (то есть со всеми тегами и ненужными скобочками) и преобразует его так, чтобы по нему было удобно искать."""

import re
def preprocess(context):
  info = {'lex': [], 'sem': [], 'tokens': [], 'sentence': ''} # словарь вида {lex: список лемм, sem: список семантических тегов, tokens: список словоформ, sentence: контекст в виде удобочитаемой строки}
  pattern = r'<w>.+?</w>' # с помощью ? мы можем сделать наше регулярное выражение нежадным!!
  words = re.findall(pattern, context) # добыли "слова", но тоже пока что в некрасивом виде

  tokens = []
  for word in words:
    lex_pattern = r'lex=\'.+?\''
    lex_raw = re.search(lex_pattern, word)
    if lex_raw:
      lex = lex_raw.group().split('=')[1].strip("'")  # нашли лексему
      info['lex'].append(lex) # добавили лексему в наш словарь


    sem_pattern = r'sem=\'.+?\''
    sem_raw = re.search(sem_pattern, word)
    if sem_raw:  # проверяем, что совпадение найдено (не у всех слов есть семантика)
      sem = sem_raw.group().split('=')[1].strip("'").split()  # нашли семантику, причём в список добавляем семантический тег не единой строкой, а списком, чтобы иметь возможность искать по отдельным тегам, а не по всему в куче
      info["sem"].append(sem) # добавили семантические теги в наш словарь

    form_pattern = '>\w+<'
    form_raw = re.search(form_pattern, word)
    if form_raw:
      form = form_raw.group().strip('<>')  # нашли словоформу
      info['tokens'].append(form) # добавили словоформу в наш словарь
      tokens.append(form) # добавили найденную словоформу в список всех словоформ данного предложения

  # Соберём все слова в одно предложение-контекст
  sentence = ' '.join(tokens)
  info['sentence'] = sentence # добавили полученное предложение в наш словарь

  return info # возвращаем словарь с полной информации о данном контексте

"""**Словарь во всеми контекстами из файла**"""

for i in tqdm(range(len(context))):
    ctx = context[i]
    print(f'Индекс: {i}, длина контекста: {len(ctx)}')
    if ctx.strip() == '':
        print('Пустой контекст')
    else:
        print(ctx[:100])  # покажем первые 100 символов
    full_info[i] = preprocess(ctx)

"""**Поиск по токену** - Функция, которая на вход получает токен (словоформу), а на выход отдаёт контексты, в которых встречается эта словоформа."""

def find_by_token(token):
  good_contexts = [] # список предложений, содержащий данную словоформу
  for i in range(len(full_info)):
    tokens = full_info[i]['tokens']
    sentence = full_info[i]['sentence']
    if token in tokens:
      good_contexts.append(sentence)

  return good_contexts

find_by_token('ключ')

"""**Поиск по лемме** - Подаём на вход лемму, на выходе получаем предложения, содержащие любые формы данной леммы.


"""

def find_by_lemma(lemma):
  good_contexts = []
  for i in range(len(full_info)):
    lemmas = full_info[i]['lex']
    sentence = full_info[i]['sentence']
    if lemma in lemmas:
      good_contexts.append(sentence)

  return good_contexts

find_by_lemma('сова')

"""**Поиск по отдельному семантическому тегу**"""

def find_by_tag(tag):
  good_contexts = []
  for i in range(len(full_info)):
    sem = full_info[i]['sem'] # список со списками тегов
    sentence = full_info[i]['sentence']
    for tag_set in sem:
      if tag in tag_set:
        good_contexts.append(sentence)
        continue

  return list(set(good_contexts))

find_by_tag('t:animal')

"""**Поиск по набору семантических тегов** - Хотим вывести предложения, в которых встречаются слова, обладающие именно заданной комбинацией семантических тегов (не больше и не меньше). Пишем теги через ПРОБЕЛ."""

def find_by_tags(tags):
  good_contexts = []
  tagset = set(tags.split())
  for i in range(len(full_info)):
    sem = full_info[i]['sem']
    sentence = full_info[i]['sentence']
    for t in sem:
      if tagset.issubset(set(t)):
        good_contexts.append(sentence)
        break
  return good_contexts

print(find_by_tags('r:concr t:hum'))

"""**Подсчет частотности токенов, лемм, тегов, комбинаций тегов**

*Частотность токенов*
"""

def count_tokens(token):
  c = 0 # счётчик: сколько раз данный токен встречается в датасете
  for i in range(len(full_info)):
    tokens = full_info[i]["tokens"]
    for t in tokens:
      if t == token:
        c += 1

  return c

count_tokens('лист')

"""*Частотность лемм*"""

def count_lemmas(lemma):
  c = 0
  for i in range(len(full_info)):
    lemmas = full_info[i]['lex']
    for l in lemmas:
      if l == lemma:
        c += 1

  return c

count_lemmas('сова')

"""*Частотность семантических тегов*"""

def count_tags(tag):
  c = 0
  for i in range(len(full_info)):
    sem = full_info[i]['sem'] # список со списками тегов
    for s in sem:
      for t in s:
        if t == tag:
          c += 1

  return c

count_tags('r:concr')

"""*Частотность комбинаций тегов (надо вводить несколько тегов через пробел)*"""

def count_tagsets(tags):
  c = 0
  tagset = tags.split()
  for i in range(len(full_info)):
    sem = full_info[i]['sem'] # список со списками тегов
    for s in sem:
      if set(tagset) == set(s):
        c += 1

  return c

count_tagsets('r:concr t:animal')

"""---

# PANDAS

**Предобработка данных**
"""

import pandas as pd
from bs4 import BeautifulSoup as bs
# BeautifulSoup —  библиотека, которая читает и разбирает XML/HTML-файлы как структуру дерева.

def search_token_contexts(xml_content, token, window=5):
    """
    Ищем все контексты, где встречается слово `token`.
    window — количество слов до и после слова.
    """
    # Преобразуем XML в структуру BeautifulSoup
    soup = BeautifulSoup(xml_content, 'lxml')

    # Находим все теги <w>, где обычно находятся слова
    words = soup.find_all('w')

    # Достаём текст из каждого тега <w>
    tokens = [w.get_text() for w in words]

    # Список для хранения найденных контекстов
    contexts = []

    # Приводим слово к нижнему регистру для нечувствительности к регистру
    token_lower = token.lower()

    # Перебираем все слова
    for i, word in enumerate(tokens):
        # Если найдено совпадение (без учёта регистра)
        if token_lower in word.lower():
            # Начало контекста (не меньше 0)
            start = max(i - window, 0)
            # Конец контекста (не больше длины текста)
            end = min(i + window + 1, len(tokens))

            # Получаем отрывок слов вокруг токена
            context = tokens[start:end]

            # Объединяем в одну строку и добавляем в список
            contexts.append(' '.join(context))

    # Возвращаем список контекстов
    return contexts

with open('/content/nozhnitsy.txt', encoding='utf-8', errors='ignore') as f:
    content = f.read()
print(content[:500]) #выводим первые 500 символов файла

"""**Открываем файл nozhnitsy.txt, в котором содержится текст в формате XML.**"""

# ищем слово 'ножницы' в тексте
results = search_token_contexts(content, 'ножницы')

# количество найденных контекстов и сами контексты
print(f"Найдено {len(results)} контекстов для токена 'ножницы':")
for c in results:
    print(c)

"""**поиск контекстов по заданной лемме**"""

def lemmatize_token(token):
    parsed_word = morph.parse(token)[0]
    return parsed_word.normal_form

# Функция для поиска контекста по лемме слова (без подсчёта)
def print_context_lemma(file_path, token, context_size=7):
    with open(file_path, 'r', encoding='utf-8') as file:
        content = file.read()

    soup = BeautifulSoup(content, 'lxml')
    w_tags = soup.find_all('w')

    printed_contexts = set()
    lemma_token = lemmatize_token(token)

    print(f'🔍 Поиск по лемме: "{lemma_token}"\n')

    for w_tag in w_tags:
        lemmas = [lemmatize_token(word) for word in w_tag.text.split()]
        if lemma_token in lemmas:
            try:
                w_index = list(w_tag.parent.children).index(w_tag)
            except ValueError:
                continue

            context_words = []
            for i in range(max(0, w_index - context_size), min(len(w_tag.parent.contents), w_index + context_size + 1)):
                child = w_tag.parent.contents[i]
                if isinstance(child, NavigableString):
                    continue
                if child.name == 'w':
                    context_words.append(child.text.strip())

            context_text = ' '.join(context_words)

            if context_text not in printed_contexts:
                print(f'→ {context_text}')
                printed_contexts.add(context_text)

file_path = '/content/nozhnitsy.txt'
token = 'ножницами'
print_context_lemma(file_path, token, context_size=7)

"""# **Поиск и извлечение данных**

**Токены** - поиск по токену. Функция, которая на вход получает токен (словоформу), а на выход отдаёт контексты, в которых встречается эта словоформа. При этом под контекстов понимаем предложение, в котором встретился данный токен.
"""

def print_context_form(file_path, token, context_size=7):
    with open(file_path, 'r', encoding='utf-8', errors='ignore') as file:
        content = file.read()

    soup = BeautifulSoup(content, 'lxml')
    w_tags = soup.find_all('w')
    printed_contexts = set()
    token_lower = token.lower()

    print(f'🔍 Поиск по словоформе: "{token}"\n')

    for w_tag in w_tags:
        words_in_tag = w_tag.text.split()

        if any(word.lower() == token_lower for word in words_in_tag):
            try:
                w_index = list(w_tag.parent.children).index(w_tag)
            except ValueError:
                continue

            context_words = []
            start_idx = max(0, w_index - context_size)
            end_idx = min(len(w_tag.parent.contents), w_index + context_size + 1)

            for i in range(start_idx, end_idx):
                child = w_tag.parent.contents[i]
                if isinstance(child, NavigableString):
                    continue
                if child.name == 'w':
                    context_words.append(child.text.strip())

            context_text = ' '.join(context_words)

            if context_text not in printed_contexts:
                print(f'→ {context_text}')
                printed_contexts.add(context_text)

file_path = '/content/nozhnitsy.txt'
token = 'ножницами'
print_context_form(file_path, token, context_size=7)

"""# **Поиск контекстов по семантическому тегу**"""

# Функция для извлечения контекстов с нужным семантическим тегом из файла
def extract_contexts(file_path, semantic_tag, context_window=3):
    # Открываем файл с указанной кодировкой и читаем весь текст
    with open(file_path, 'r', encoding='utf-8') as file:
        content = file.read()

    # Разбираем текст как HTML/XML с помощью BeautifulSoup
    soup = BeautifulSoup(content, 'html.parser')
    # Находим все теги <w> — это отдельные слова в тексте
    w_tags = soup.find_all('w')
    # Создаём список для хранения контекстов
    contexts = []

    # Проходим по каждому слову (тегу <w>) с индексом i
    for i in range(len(w_tags)):
        # Ищем внутри слова тег <ana>
        ana_tag = w_tags[i].find('ana')
        # Проверяем, что тег <ana> есть, и в его атрибутах есть 'sem'
        # и что нужный семантический тег содержится в атрибуте 'sem'
        if ana_tag and 'sem' in ana_tag.attrs and semantic_tag in ana_tag['sem']:
            # Определяем начало окна контекста (не меньше 0)
            context_start = max(0, i - context_window)
            # Определяем конец окна контекста (не больше длины списка слов)
            context_end = min(len(w_tags), i + context_window + 1)
            # Берём слова из окна контекста и получаем их текст
            context_words = [w_tags[j].get_text() for j in range(context_start, context_end)]
            # Объединяем слова в строку через пробел
            context_text = ' '.join(context_words)
            # Добавляем контекст в список
            contexts.append(context_text)

    # Возвращаем список уникальных контекстов (без повторов)
    return list(set(contexts))

# Путь к файлу с текстом
file_path = '/content/nozhnitsy.txt'
# Семантический тег, который ищем в тексте
semantic_tag = 't:tool:instr'
# Вызов функции с окном контекста 3 слова (слева и справа)
contexts = extract_contexts(file_path, semantic_tag, context_window=3)

# Выводим все найденные контексты на экран
for context in contexts:
    print(context)

"""# **Поиск по комбинации семантических тегов**"""

def extract_contexts(file_path, semantic_tags, context_window=3):
    # Открываем файл с текстом в кодировке windows-1251
    with open(file_path, 'r', encoding='utf-8') as file:
        content = file.read()

    # Используем BeautifulSoup для парсинга HTML/XML содержимого
    soup = BeautifulSoup(content, 'html.parser')

    # Находим все теги <w>
    w_tags = soup.find_all('w')

    contexts = []  # Список для хранения контекстов

    # Проходим по всем тегам <w>
    for i in range(len(w_tags)):
        # Ищем внутри каждого <w> тег <ana>
        ana_tag = w_tags[i].find('ana')

        # Проверяем, что тег <ana> существует и содержит все семантические теги из списка semantic_tags
        if ana_tag and all(tag in ana_tag.get('sem', '') for tag in semantic_tags):
            # Определяем границы окна контекста (слева и справа от текущего слова)
            context_start = max(0, i - context_window)
            context_end = min(len(w_tags), i + context_window + 1)

            # Собираем слова из окна контекста
            context_words = [w_tags[j].get_text() for j in range(context_start, context_end)]

            # Объединяем слова в строку
            context_text = ' '.join(context_words)

            # Добавляем контекст в список
            contexts.append(context_text)

    # Возвращаем уникальные контексты (удаляем повторы)
    return list(set(contexts))

# Путь к файлу с текстом
file_path = '/content/nozhnitsy.txt'

# Семантические теги, которые мы ищем
semantic_tags = ['r:concr', 't:tool']
# Вызываем функцию для извлечения контекстов с окном в 2 слова с каждой стороны
contexts = extract_contexts(file_path, semantic_tags, context_window=2)

# Выводим все найденные контексты
for context in contexts:
    print(context)

"""# **Вывод результатов в ячейку**"""

# импортируем pandas для работы с таблицами
import pandas as pd

# Функция для извлечения информации из размеченного файла
def extract_info(file_path, context_window=3):
    # Открываем файл и читаем его содержимое с нужной кодировкой
    with open(file_path, 'r', encoding='utf-8') as file:
        content = file.read()

    # Разбираем содержимое как HTML/XML
    soup = BeautifulSoup(content, 'html.parser')

    # Ищем все теги <w> — каждый тег <w> представляет собой слово
    w_tags = soup.find_all('w')

    # Создаём списки, чтобы сохранить информацию
    tokens = []             # исходные слова
    lemmas = []             # леммы (нормальные формы слов)
    grammatical_tags = []   # грамматические теги
    semantic_tags = []      # семантические теги
    contexts = []           # контексты (окружающие слова)

    # Проходим по всем словам в тексте
    for i in range(len(w_tags)):
        ana_tag = w_tags[i].find('ana')  # ищем тег <ana> внутри тега <w>
        if ana_tag:
            token = w_tags[i].get_text()  # само слово (токен)
            lemma = ana_tag.get('lex', '')  # лемма
            gram = ana_tag.get('gr', '')    # грамматическая информация
            sem = ana_tag.get('sem', '')    # семантическая метка

            # Определяем окно контекста: 3 слова слева и 3 справа
            context_start = max(0, i - context_window)
            context_end = min(len(w_tags), i + context_window + 1)
            context_words = [w_tags[j].get_text() for j in range(context_start, context_end)]
            context_text = ' '.join(context_words)  # объединяем слова в строку

            # Добавляем информацию в списки
            tokens.append(token)
            lemmas.append(lemma)
            grammatical_tags.append(gram)
            semantic_tags.append(sem)
            contexts.append(context_text)

    # Создаём таблицу (DataFrame) из всех списков
    df = pd.DataFrame({
        'Token': tokens,                     # колонка: слово
        'Lemma': lemmas,                     # колонка: лемма
        'Grammatical Tags': grammatical_tags,  # колонка: грам. тег
        'Semantic Tags': semantic_tags,        # колонка: сем. тег
        'Context': contexts                    # колонка: контекст
    })

    return df  # возвращаем таблицу

# Путь к файлу
file_path = '/content/nozhnitsy.txt'

# Вызываем функцию и сохраняем результат в переменную df, и показываем таблицу на экране
df = extract_info(file_path, context_window=3)
print(df)

"""# **Подсчет частотности токенов, лемм, тегов, комбинаций тегов**"""

# Считает, сколько раз слово "ножницами" встречается в колонке "Token" (то, как написано в тексте)
#  все вхождения подстроки 'ножницами' во всей колонке Token
token_count = df['Token'].str.count('ножницами').sum()

# Считает, сколько раз лемма "ножницы" (основная форма слова) встречается в колонке "Lemma"
lemma_count = df['Lemma'].str.count('ножницы').sum()

# Считает, сколько раз встречается тег "t:animal" в колонке семантических тегов
concr_tag_count = df['Semantic Tags'].str.count('t:animal').sum()

# Считает, сколько раз одновременно встречаются два тега: "r:concr" и "t:tool"
concr_tool_tag_count = df['Semantic Tags'].apply(lambda x: 'r:concr' in x and 't:tool' in x).sum()

print(f"\nПодсчет частотности:")
print(f"Token 'ножницами': {token_count}")
print(f"Lemma 'ножницы': {lemma_count}")
print(f"Tag 't:animal': {concr_tag_count}")
print(f"Tags 'r:concr t:tool': {concr_tool_tag_count}")