# -*- coding: utf-8 -*-
"""Sumy T5 Аннотации к статьям.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dWDZtdZlfciM0xUn3O71bGoJZfclynWb
"""

!pip install sumy transformers nltk --quiet

# Импорты
import os
import pandas as pd
from tqdm import tqdm
from sumy.parsers.plaintext import PlaintextParser
from sumy.nlp.tokenizers import Tokenizer
from sumy.summarizers.lex_rank import LexRankSummarizer
from sumy.nlp.stemmers import Stemmer
import nltk
import torch
from transformers import T5ForConditionalGeneration, AutoTokenizer

nltk.download('punkt')
nltk.download('punkt_tab')
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f"Используемое устройство: {device}")

articles_path = '/content/10_articles'

texts = []
for file in sorted(os.listdir(articles_path)):
    if file.endswith(".txt"):
        with open(os.path.join(articles_path, file), 'r', encoding='utf-8') as f:
            text = f.read()
            name = file[:-4]
            texts.append((name, text))

df = pd.DataFrame(texts, columns=['name', 'text'])
print(f"Загружено {len(df)} статей")

def summarize_with_sumy(text, num_sentences=3):
    parser = PlaintextParser.from_string(text, Tokenizer("russian"))
    stemmer = Stemmer("russian")
    summarizer = LexRankSummarizer(stemmer)
    summary = summarizer(parser.document, num_sentences)
    return " ".join(str(sentence) for sentence in summary)

print("\n--- АННОТАЦИИ С SUMY ---\n")
sumy_annotations = []
for i, row in df.iterrows():
    summary = summarize_with_sumy(row['text'])
    sumy_annotations.append(summary)
    print(f"Статья {row['name']}:\n{summary}\n")

# ============ T5 ============

print("\nЗагружаем модель T5...")
model_name = "IlyaGusev/rut5_base_sum_gazeta"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = T5ForConditionalGeneration.from_pretrained(model_name).to(device)

def summarize_with_t5(text):
    input_ids = tokenizer(
        [text],
        max_length=600,
        add_special_tokens=True,
        padding="max_length",
        truncation=True,
        return_tensors="pt"
    )["input_ids"].to(device)
    output_ids = model.generate(
        input_ids=input_ids,
        min_length=30,
        max_length=250,
        no_repeat_ngram_size=3
    )[0]
    return tokenizer.decode(output_ids, skip_special_tokens=True)

print("\n--- АННОТАЦИИ С T5 ---\n")
t5_annotations = []
for i, row in df.iterrows():
    summary = summarize_with_t5(row['text'])
    t5_annotations.append(summary)
    print(f"Статья {row['name']}:\n{summary}\n")

df['annotation_sumy'] = sumy_annotations
df['annotation_t5'] = t5_annotations

# Вывод объединённого DataFrame
print("\n=== ИТОГОВАЯ ТАБЛИЦА ===\n")
print(df[['name', 'annotation_sumy', 'annotation_t5']])

# ✅ Сохранение в CSV с правильной кодировкой
df.to_csv('annotations_combined.csv', index=False, encoding='utf-8-sig')
print("\nФайл сохранён")

import pandas as pd
from IPython.display import display

# Содержимое таблицы
data = {
    "Критерий": [
        "Связность текста",
        "Фактологическая точность",
        "Соответствие теме",
        "Структура аннотации",
        "Охват ключевых идей",
        "Подходит как аннотация"
    ],
    "Реальная аннотация": [
        "✅ Полноценный связный научный текст",
        "✅ Указаны конкретные алгоритмы, параметры, результаты",
        "✅ Полностью по теме статьи",
        "✅ Научный стиль, введение → метод → вывод",
        "✅ SCRYPT, SHA512, GOST, параметры, производительность",
        "✅ Да"
    ],
    "T5": [
        "✅ Связный, написано как 'под человека'",
        "⚠️ Ошибка: соль помогает взлому, пример LinkedIn без контекста",
        "⚠️ Вокруг темы, но без привязки к исследуемым алгоритмам",
        "⚠️ Похоже на публицистический пересказ",
        "⚠️ Общая тема про 'пароли', без конкретики",
        "⚠️ Больше как новостной обзор"
    ],
    "Sumy": [
        "❌ Обрывки предложений, фрагменты без логики",
        "✅ Упомянуты BCRYPT, раунды, корректные термины",
        "✅ В тему, но обрывочно",
        "❌ Нет логического порядка, просто набор предложений",
        "✅ Частично отражает идею про раунды и защиту",
        "⚠️ Ближе к выдержкам из середины статьи, не как аннотация"
    ]
}

# Создание DataFrame
df_comparison = pd.DataFrame(data)

# Отображение таблицы
display(df_comparison)